name: Práctico 02

on:
  push:
    branches: "**2**"

  workflow_dispatch:

jobs:

  basic-test:
    name: Test Básicos

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Dependencies
        run: pip install pytest

      - name: Cambiar al directorio practico_02
        run: cd practico_02


      - name: Run Basic Tests
        run: pytest practico_02/practico_02_test.py


  style-test:
    needs: basic-test
    name: Verificación de Estilo (Flake8)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Flake8
        run: pip install flake8

      - name: Test Style
        run: flake8 practico_02 --count --max-complexity=10 --max-line-length=130 --ignore=E266,F401,E402 --statistics --show-source

